### ISSUE TITLE
HasRequiredTraits documentation is garbled

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#1005]
The rendered version of the `HasRequiredTraits` documentation doesn't look like wot it oughta.

<img width="1107" alt="Screenshot 2020-04-14 at 17 30 06" src="https://user-images.githubusercontent.com/662003/79346268-1079e780-7f2a-11ea-849a-8ef0278668d8.png">

**Comment by ievacerny** [comment]
This is because of `Usage` section which isn't in Numpy docstring format. Best equivalent is most likely `Examples`:

![image](https://user-images.githubusercontent.com/25366751/80365656-dc82b880-887f-11ea-9266-4f3f09dc7d80.png)


I see a lot more rendering issues in documentation, mainly with the use of `Description` section (should be just blocks of text after one line description) and class/function mixups (e.g. Property). Should I go through docs and fix all of these as well?

**Comment by mdickinson** [comment]
> Should I go through docs and fix all of these as well?

If you have the energy, yes please! Though I'm also fine with a fixing-things-as-we-notice-them approach.

**Comment by mdickinson** [comment]
And yes, `Examples` sounds good here.
