### ISSUE TITLE
Remove traits_super

### ISSUE THREAD

**Issue by kitchoi** [enthought/traits#1013]
This class was introduced a long time ago (older than Traits 2 or maybe even older):
https://github.com/enthought/traits/blob/2685c7a260228fe535582606c72f892dac8ccb9a/traits/has_traits.py#L3396-L3404

There are no evidence that suggests this is needed. We should remove it.

**Comment by mdickinson** [comment]
Let's do this for 6.1

**Comment by mdickinson** [comment]
FTR, this was introduced 13 years ago in e9a6387e82aba6ea9b83e1a284b6d6d032b4f331 (in the Git history, though the original SVN repo may have had more information), and is referred to in exactly three commits since then, all of which are general clean-up commits. It's not used anywhere in current Traits or at any point in the Git history for Traits. It's not used anywhere else in ETS, or in any of the private Traits-using projects that I have access to. It's undocumented, untested, and the functionality it provides appears to be both (a) a bad idea, and (b) poorly implemented.

It deserves to be removed several times over. I'm just sad that we can only remove it once.
