### ISSUE TITLE
Add NoDefaultSpecified from trait_type to traits.api

### ISSUE THREAD

**Issue by corranwebster** [enthought/traits#1041]
This is the constant used to indicate that a trait `__init__` method is not being supplied with a default override.  This is helpful to have available for advanced users who are writing new `TraitType` subclasses and need to handle possible missing `default_value` parameters.

**Comment by mdickinson** [comment]
Sounds good to me. It moves us away from the antipattern of using `Undefined` for this.

**Comment by kitchoi** [comment]
Ah I did not notice this issue earlier. `NoDefaultSpecified` is now made a private class. See https://github.com/enthought/traits/issues/1379

**Comment by kitchoi** [comment]
> It moves us away from the antipattern of using Undefined (or Missing) for this.

Just wanted to mention that I am puzzled by this statement - maybe there is a documentation opportunity somewhere.

**Comment by mdickinson** [comment]
> Just wanted to mention that I am puzzled by this statement - maybe there is a documentation opportunity somewhere.

`Undefined` and `Missing` have quite specific intended use-cases; using them as default-value sentinels for no other reason than that they're singletons is an abuse. I'm not sure what the documentation opportunity would be - it's more a case of not using things for uses that they're not intended for.

**Comment by mdickinson** [comment]
Or in other words, I suspect that the thought process that led to existing (now removed) uses of `Missing` as a default value were no more sophisticated than:

1. We need a default-value sentinel for such-and-such an optional argument, so that we can distinguish calls  that provide that argument from calls that don't.
2. We can't follow the common practice of using `None` as that default-value sentinel, because `None` is a legitimate value that might be passed explicitly.
3. So we need something else.
4. Oh look: `Missing` is a singleton, and it already exists, so we don't have to write any new code. Let's use that.

The way to stop that happening again is better quality code review rather than documentation.

**Comment by mdickinson** [comment]
With all that said, I am uncomfortable about the fact that we have a class (`TraitType`) that's designed to be subclassed, and that the default value for `default_value` (getting a bit meta here ...) in its `__init__` method is now inaccessible. Given that subclasses are likely to want to extend the `__init__` method, they should probably have access to that default value.

Without access to that default value, subclasses potentially have to do an awkward dance of making two separate `__init__` superclass calls in separate paths - one for the case where the default value is passed, and one where it isn't, instead of being able to simply pass `NoDefaultSpecified` to simulate the case of no default value.

I'm leaning towards reverting all the changes in #1379, and the preceding changes that motivated those. The original issue that motivated all of this change was a pure documentation issue, and in hindsight I think we should have made a documentation-only fix and left `NoDefaultSpecified` as it was.
