### ISSUE TITLE
Unify APIs for TraitChangeEvent and ListChangeEvent?

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#1084]
[Taken from a [comment](https://github.com/enthought/traits/pull/1071#discussion_r423182547) by @corranwebster in discussion for PR #1071, regarding the `ListChangeEvent`]

> Also, a design suggestion for this and the other collection change events: it might make sense to try to mimic the API of TraitChangeEvent. At a minimum:
> 
> using object instead of trait_list
> a dummy attribute name which is always "items"
> This might allow code to consume both types of event without having to do a type check if it only cares about the object and the name.
> 
> That would imply an implicit "ChangeEvent" interface where you expect both "object" and "name" to exist. It is tempting to make new be the new value of the list (ie. the same as object) and old to be a property that lazily reconstructs the old value of the list from the added and removed, but that isn't really right from a philosophical point of view.
> 
> Really the rest of the information is the "delta", ie. we have
> 
> "who changed": the object that was changed, be it a HasTraits, TraitList, etc.
> "what changed": the name of the thing that changed (the thing that was being observed)
> "how it changed": the nature of the changes that took place (old/new, added/removed, etc.)
> Thinking this way may help with the design of these classes.

We're merging #1071 without this suggested change for now; this issue is to remind us to revisit this once the observer work is more complete but prior to the 6.1.0 release.

**Comment by kitchoi** [comment]
Offline discussion:

@corranwebster  and I agree that `object` is the right attribute name for representing "who is changed", e.g. `HasTraits` for `TraitChangeEvent`, `TraitList` for `ListChangeEvent`.  Although `object ` has always been an instance of `HasTraits` in the existing `on_trait_change` machinery for `*_items` events, it should not be too hard to adjust to the new meaning.

We did not discuss whether to have `name` for all event objects.

As for whether to group attributes to create a nested data structure, no consensus so far: it is a choice between "Namespaces are one honking great idea" and "Flat is better than nested".

**Comment by corranwebster** [comment]
Related to this, are the other things which we might want to add to the event object?  Obvious candidates would be things like if you do `foo.observe(callback, "bar.baz.wom")` then having both `foo` (the base object for the listener) and `"bar.baz.wom"` passed in might be useful.  Not essential, obviously, as these could be passed in via a closure or callable object if needed, but if it were easy to make these available it might save some code.

It would be _very_ nice to be able to give even more context (like was it `foo.bar.baz` that fired, in particular, rather than `foo.bar` or `foo.bar.baz.wom`) but you run up against ambiguity once you get beyond trivial situations.

**Comment by mdickinson** [comment]
On the flat versus nested, I think we can postpone and revisit after 6.1.0 is released - we're marking the API as provisional.

+1 to rename the observed object to `object` throughout these classes, but I'd suggest we leave any other changes until after the release.

**Comment by mdickinson** [comment]
There are still some unaddressed parts of this issue. Re-opening and assigning to the 6.2.0 milestone.

**Comment by mdickinson** [comment]
This doesn't need  to be resolved for the 6.2 release; bumping to 6.3. We're planning a lot of migration work on the rest of ETS to move things to the `observe` framework; if that migration bumps into this issue, that  should boost its priority. If it doesn't, that may be an indication that no action is needed prior to declaring the APIs stable.

**Comment by aaronayres35** [comment]
+1 for adding `name` on `ListChangeEvent`

TraitsUI wants to do things with a name when listening to changes of the items in a container.  e.g.:
https://github.com/enthought/traitsui/blob/7a6d46ad10ea6c6b5a8dcc3b4939a9670c2a52ad/traitsui/qt4/tree_editor.py#L1373-L1374

this wants to ultimately create a `ListUndoItem` which expects a trait name.

https://github.com/enthought/traitsui/blob/7a6d46ad10ea6c6b5a8dcc3b4939a9670c2a52ad/traitsui/qt4/tree_editor.py#L1382

**Comment by kitchoi** [comment]
> TraitsUI wants to do things with a name when listening to changes of the items in a container. e.g.:
https://github.com/enthought/traitsui/blob/7a6d46ad10ea6c6b5a8dcc3b4939a9670c2a52ad/traitsui/qt4/tree_editor.py#L1373-L1374

From what I can see, the `name = name[:-6]` removes the "_items" in the `self.children + "_items"` in this line:
https://github.com/enthought/traitsui/blob/7a6d46ad10ea6c6b5a8dcc3b4939a9670c2a52ad/traitsui/tree_node.py#L268

So the logic was to try to retrieve the trait name for which the trait list is defined on an object.
This name can be obtained directly from `ListChangeEvent.object.name`, because `ListChangeEvent.object` would be an instance of `TraitListObject`, which has a `name`: 
https://github.com/enthought/traits/blob/6e924d2189d2c2f22b0e8b8b961ce2597f586671/traits/trait_list_object.py#L563-L564

**Comment by mdickinson** [comment]
I'm going to re-close this. Adding `name` to the `ListChangeEvent` seems messy, with unclear semantics (what should the name be in the case that the `List` is nested inside another trait?).

If `foo` is a List-valued trait on an object, I'd recommend against the pattern of doing

```python
@observe("foo.items")
def _react(self, event):
    <do_something_with_event>
```

Instead, write two separate handlers: one for pattern `foo:items` and one with pattern `foo`. Often those handlers will need to do different things anyway. In the cases where they need to do the same thing, both can call a suitable utility method.
