### ISSUE TITLE
AttributeError: 'TraitCompound' object has no attribute 'clone'

### ISSUE THREAD

**Issue by servoz** [enthought/traits#1092]
Hello,
Let's say I want to create, using the Traits package, a "bases" attribute that can be a 'none' string or a dictionary with keys which are ‘hrf’ or ‘fourier’ or ‘fourier_han’ or ‘gamma’ or ‘fir’ and with values which are a dictionary with keys which are ‘derivs’ or ‘length' or ‘order’ and with values which are a list or a float). Ex:

> bases == 'none'
> or
> bases == {'hrf': {'derivs': [0, 0]}}
> or
> bases == {'fourier': {'length': 1.4, 'order': 3}}

if I define a 'none' string or a dictionary with keys which are ‘hrf’ or ‘fourier’ or ‘fourier_han’ or ‘gamma’ or ‘fir’ and with values which are a dictionary with keys which are ‘derivs’ or ‘length' or ‘order’ and with values which are a list) it's working fine:

```
>>> import traits.api as traits
>>> class Foo(traits.HasTraits):
...  bases = traits.Either(traits.Dict(traits.Enum("hrf","fourier","fourier_han","gamma","fir"),traits.Dict(traits.Enum("derivs","length","order"), traits.List)),'none',default={"hrf":{"derivs":[0,0]}})
... 
>>> foo=Foo()
>>> foo.bases
{'hrf': {'derivs': [0, 0]}}

```
But this is not exactly what I want. If now I try to give the possibility to use list or float in the inside dictionary, it's not working:

 ```
>>> import traits.api as traits
 >>> class Foo(traits.HasTraits):
...  bases = traits.Either(traits.Dict(traits.Enum("hrf","fourier","fourier_han","gamma","fir"),traits.Dict(traits.Enum("derivs","length","order"), traits.Either(traits.List, traits.Float))),'none',default={"hrf":{"derivs":[0,0]}})
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in Foo
  File "/home/econdami/.local/lib/python3.7/site-packages/traits/trait_types.py", line 2804, in __init__
    handler = handler.clone()
AttributeError: 'TraitCompound' object has no attribute 'clone'
```

why ?

**Comment by kitchoi** [comment]
Thank you @servoz!
Confirmed that this error still exists on master.

On master, there is a new trait type `Union` which is preferred to `Either` in general. It should be able to support your use case. The next release of Traits (6.1) should include this trait type.  Please wait for the release (the master branch is also free to be used but breakages will be expected on the bleeding edge).

With `Union`, your example can be written like this:
```
import traits.api as traits

class Foo(traits.HasTraits):
    bases = traits.Union(
        traits.Dict(traits.Enum("hrf","fourier","fourier_han","gamma","fir"),
        traits.Dict(
            traits.Enum("derivs","length","order"),
            traits.Union(traits.List, traits.Float),
        )),
        traits.Enum(['none']),
        default_value={"hrf":{"derivs":[0,0]}}
    )
```

However I'd like to highlight the use of `default_value` there.  In order for traits to carry out validation on a container, the container needs to be transformed. Since static default values are not validated, traits cannot validate mutations on the default value.

Here is what this means:
```
foo = Foo()
print(foo.bases)    # {"hrf": {"derivs": [0, 0]}
foo.bases["hrf"]["derivs"] = "1.0"   # oops: no errors
print(type(foo.bases["hrf"]))     # <class 'dict'>
```

If the value is set by other means, the validation would work:
```
foo = Foo()
foo.bases = {"hrf": {"derivs": [0,0]}}

print(type(foo.bases["hrf"]))     # <class 'traits.trait_dict_object.TraitDictObject'>

foo.bases = "none"    # ok
foo.bases = {"hrf": {"derivs": 1.0}}  # ok
foo.bases["hrf"]["derivs"] = "1.0"    # TraitError (expected)
```

Your report has led to the discovery of https://github.com/enthought/traits/issues/1104 (which is now fixed). So thank you very much!

**Comment by servoz** [comment]
Dear @kitchoi,

thank you very much for your very detailed and effective answer and for the work that has been done to solve the problems.

We use the Traits project a lot in our project and we are very happy that you are so responsive in trying to constantly improve it.

As far as I am concerned, this ticket can now be closed!

Thanks again
