### ISSUE TITLE
Missing notification for shadow trait on first set of the main trait

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#1183]
A listener to a shadow trait of a mapped trait should be fired the first time that the main trait is set (assuming it's set to a value not equal to the original default). That happens under Traits 6.0.0, but not under master.

This changed with #1091.

Here's a script to reproduce. With Traits 6.0.0, this shows two change notifications. With current master, it only shows one.

```python
from traits.api import HasTraits, Map, on_trait_change

class A(HasTraits):
    color = Map(
        {"red": 0xff0000, "green": 0x00ff00, "blue": 0x0000ff},
        default_value="green",
    )

    @on_trait_change("color_")
    def _report_color_change(self, obj, name, old, new):
        print(f"Color changed from {old:#08x} to {new:#08x}")

a = A()
a.color = "red"
a.color = "blue"
```

Output on my machine:
```
(traits) mirzakhani:traits mdickinson$ python ~/Desktop/test.py 
Color changed from 0xff0000 to 0x0000ff
```

**Comment by mdickinson** [comment]
Here's a simpler example that doesn't depend on enable:

```python
from traits.api import HasTraits, Map, on_trait_change


class A(HasTraits):
    color = Map(
        {"red": 0xff0000, "green": 0x00ff00, "blue": 0x0000ff},
        default_value="green",
    )

    @on_trait_change("color_")
    def _report_color_change(self, obj, name, old, new):
        print(f"Color changed from {old:#08x} to {new:#08x}")


a = A()
a.color = "red"
a.color = "blue"
```

I expect to see two notifications. Instead, I see only one:
```
(traits) mirzakhani:traits mdickinson$ python ~/Desktop/test.py 
Color changed from 0xff0000 to 0x0000ff
```

**Comment by mdickinson** [comment]
Marking as blocking for the release.

**Comment by mdickinson** [comment]
I deleted the second comment here and merged its contents into the main description, so that we have a simple description of the bug that doesn't depend on Enable.

**Comment by kitchoi** [comment]
Agreed this is blocking indeed.

Some thoughts on why this happened, but I haven't verified:

When the main trait `color` is assigned the first time, it triggers the mapped trait `color_` to be assigned. on_trait_change tries to fetch the "old" value for `color_`, which is supposed to be the default. But because of the change in #1091 (it fixed another legitimate bug), the default value (i.e. the "old" value) of the mapped trait is dynamically calculated from the main trait, after it has already been changed. Consequently the "old" value equals the "new" value and the change event is not fired.
