### ISSUE TITLE
Building from source

### ISSUE THREAD

**Issue by dethorpecs** [enthought/traits#1203]
Hi guys,
traits 6.0.0 is needed for my installation of mayavi but has not yet found it's way into pip. 
Does someone have a minute to help a novice build 6.0.0 from source?

ERROR: Could not find a version that satisfies the requirement traits==6.0.0 (from versions: 4.4.0, 4.5.0, 4.6.0, 5.0.0, 5.1.0, 5.1.1, 5.1.2, 5.2.0)

In the 6.0.0 running setup I have run afoul when running pythong setup.py
TypeError: write() argument 1 must be unicode, not str

And 6.1.0 throws
TypeError: 'encoding' is an invalid keyword argument for this function

I assume I am just lost in the weeds. Any advice?

**Comment by mdickinson** [comment]
Are you using Python 2 or Python 3? Traits versions 6.0.0 and above require Python 3.5 or later. The error messages you show sound like errors that I'd expect from Python 2.

For Python 3, Traits 6.0 *is* available from PyPI, so you shouldn't need to build from source: try `python -m pip install traits==6.0.0`, making sure to use the correct `python`. (Depending on your operating system and setup, you may need to write `python3` instead of `python`.)

**Comment by mdickinson** [comment]
On the topic of building from source, it should be as easy as running `python -m pip install .` from the top-level `traits` directory, provided that you have the right version of Python.

**Comment by mdickinson** [comment]
I'm going to close this here, because there's nothing for Traits itself to change; feel free to ask continued questions on this issue, though. There's also a mailing list at ets-users@googlegroups.com that you can use for questions related to Traits, Mayavi, and other parts of ETS.
