### ISSUE TITLE
Document traits.api and backwards compatibility guarantees

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#1213]
Almost all packages that *use* Traits should be able to get by with `traits.api` and the other subpackage `api` modules; exceptions are close "friends" of Traits like TraitsUI and Envisage (though even those should possibly not be exceptions to the rule).

So there's an unwritten rule that if, as a Traits user, you import things other than from `traits.api`, `traits.adaptation.api`, `traits.observation.api`, etc., then you're on your own with respect to backwards compatibility.

We should make that rule explicit in the documentation.

**Comment by kitchoi** [comment]
It would be nice to do a brief review / show-hand to see if there are anything commonly imported outside of `traits.*.api`. Then those components to the `api` module, making it easier for developers to keep an eyes on their backward compatibility.

e.g. `ETSConfig` is commonly imported but left out of `api`.

**Comment by kitchoi** [comment]
> e.g. ETSConfig is commonly imported but left out of api.

Sorry, I was wrong, it is in `traits.etsconfig.api`, just not `traits.api`.

**Comment by mdickinson** [comment]
> It would be nice to do a brief review / show-hand to see if there are anything commonly imported outside of `traits.*.api`.

Agreed. I did a quick review of another (Enthought-internal) Traits-using project. Almost entirely `traits.api`, with a few non-api imports that were easy fixes. Here are the three non-api imports that weren't easy fixes:

```
from traits.interface_checker import check_implements, InterfaceError
from traits.util.weakiddict import WeakIDKeyDict
from traits.trait_notifiers import notification_exception_handler
```

**Comment by mdickinson** [comment]
Related to the `traits.traits_notifiers` import: I've found some cases of code outside Traits overwriting the `handle_exception` function. But I'm not sure why it's doing that - it seems unnecessary, given the existence of `pop_exception_handler` and `push_exception_handler`, which are made available in `traits.api`.

Here's one example, from TraitsUI: https://github.com/enthought/traitsui/blob/dd26a52c2840ccca250e1787adfe60c43237132f/traitsui/tests/_tools.py#L57-L66

@kitchoi Any idea why we're not using `pop_exception_handler` and `push_exception_handler` instead in the above code?

**Comment by mdickinson** [comment]
> Any idea why we're not using `pop_exception_handler` and `push_exception_handler` instead in the above code?

And the answer is probably the thread-local nature of the handler stacks. OTOH, raising exceptions on background threads is unlikely to be the right thing to do.

**Comment by kitchoi** [comment]
@mdickinson When I saw that block of code, I did think: "Hmm, this should be replaced with `pop_exception_handler` and `push_exception_handler`". But I have not got around to try that amid all the other things that are happening.  This may be anecdotal and probably orthogonal: that context manager is quite useful for capturing exceptions that occur from the GUI thread(s?), but that's the work of `sys.excepthook`.

**Comment by kitchoi** [comment]
> Any idea why we're not using pop_exception_handler and push_exception_handler instead in the above code?

Sorry, I haven't answered the question... I don't have a confident answer for you I'm afraid.

**Comment by mdickinson** [comment]
Hmm. For the GUI frameworks we care about, there should only be one GUI thread that Python ever sees, and that's the main thread.

**Comment by kitchoi** [comment]
At the moment, with this unwritten rule at the back of Traits developers' mind, things that are not in the api module are both public and internal. They are public following [PEP8 convention](https://www.python.org/dev/peps/pep-0008/#public-and-internal-interfaces) and that we have to assume users assume that convention, but they are also internal following the unwritten rule. It is hard to work with two incompatible conventions - sometimes changes assume one convention and sometimes changes assume another.

Even after the proposed clause is added, this conflicting mindset is not going to go away because Traits developers aim to be responsible. The hope is that in the long term, the clause will have bedded in in people's heads, as deeply ingrained as PEP8 convention is, then Traits developers will freely make backward incompatible changes to things that are not exposed in api modules.

However it is not very well defined when this long term goal is reached. We risk having to work with the two conflicting conventions indefinitely.

We discussed this offline (no resolution of any kind) but I just wanted to record some alternatives that were raised related to this issue, so when one comes back to this issue, they are not lost:

The documentation could say that in some future major release, things not exposed in the api module will be made internal by renaming with leading underscore. We let that clause stay there for a while, keep mentioning this in release notes. After that major release where the renaming happens, any existing usage of things not exposed will break but can be fixed by importing the internally named things again, but we hope that by that time, there is virtually nothing like that.

Ideally, one should put up deprecation warnings for that, but as we observed that most users are importing from api module already, this might be more work than necessary.

The difference this makes is that both developers of Traits and users of Traits can follow the usual convention. And there will be a well defined point in time (the major release) where more things in Traits are declared internal.
