### ISSUE TITLE
Status of CamelCaseToPython class

### ISSUE THREAD

**Issue by aaronayres35** [enthought/traits#1279]
This issue is concerned with the use of the CamelCaseToPython Functor class in another project.  
Is this class anticipated to be removed from traits in the future?/Should this dependency be avoided?

**Comment by rahulporuri** [comment]
Note that there are no users of `CamelCaseToPython`, `camel_case_to_python` or `camel_case_to_words` in traits or traitsui. I do find one use in pyface https://github.com/enthought/pyface/blob/master/pyface/workbench/i_view.py and another in apptools https://github.com/enthought/apptools/blob/master/apptools/scripting/recorder.py

**Comment by mdickinson** [comment]
Official policy (which still needs properly documenting): if it's not made available in any of the `.api` modules, use it at your own risk. See #1213 

While it's not deprecated right now, if it's unused within ETS, then `CamelCaseToPython` would be a strong candidate for future removal.

**Comment by mdickinson** [comment]
Ah, sorry; I didn't read @rahulporuri's message properly - it is still used in a few places in ETS, but that's fine - we have control of ETS, and we know where to look to fix things if we ever want to remove `CamelCaseToPython`.

So the answer to your "Should this dependency be avoided?" question is: "Yes, the dependency should be avoided!"  It's fine within ETS, but because it's not in any of the `.api` modules we're not making any guarantees for users outside ETS.

**Comment by mdickinson** [comment]
@aaronayres35 Does this answer your question? If so, we should open an issue for the downstream project, and close this one.

**Comment by aaronayres35** [comment]
> @aaronayres35 Does this answer your question? If so, we should open an issue for the downstream project, and close this one.

Yes, thank you!  I will do that
