### ISSUE TITLE
Range - Discards numpy type information

### ISSUE THREAD

**Issue by dgoeries** [enthought/traits#1324]
Hi all,

with traits 6.0.0 we experience a different `Range` behavior. We are using `numpy` types which are not preserved anymore.

```
import numpy as np
from traits.api import HasStrictTraits, Int, Range


class Binding(HasStrictTraits):
    value = Range(low=0, high=20, value=0, exclude_high=True)


binding = Binding()
binding.value = np.uint64(10)

print(binding.value, type(binding.value))
```

Until traits 5.2.0 the numpy type is preserved and we get a value of numpy type back. This changes with traits >= 6.0.0 providing integers.

Can we have the old behavior back?

**Comment by dgoeries** [comment]
@jwiggins do you have suggestions otherwise :-)

**Comment by kitchoi** [comment]
As a user of Traits, I would also be in favour of the old behaviour of leaving the value unchanged. However I believe there is a wider consistency issue here: A lot of trait types follow the convention of including transformation/normalization in validation. In a sense, the change in Traits 6 makes Range more consistent with other trait types that do this sort of transformation.

**Comment by jwiggins** [comment]
Hey Dennis! Good to see y'all are still using traits.

Is there a non-trivial amount of code dependent on the old behavior? If that is the case, then I think my recommendation would be to create your own `Range` `TraitType` implementation. Is that reasonable, or would it require touching code that's not under your control?

Another question might be: How badly do you need to upgrade? It might be OK to stay pinned to the older version of traits while strategizing a way to adapt code to the new behavior.

I'm curious why it matters that numpy types are returned... What I remember from the GUI binding code was that `Range` was used so that scalar numpy types wouldn't be needed... Just looking at `binding.value` wouldn't tell you the type (without digging around in trait metadata), but `Range` does take care of making sure that anything written to the proxy would be legal values (from either the network or the GUI side).

If you need bindings that hold numpy values, then you should probably be explicit about that and use `Instance(<numpy type>)`. From your short explanation it sounds like an instance of [Hyrum's Law](https://www.hyrumslaw.com/) rearing its ugly head. Sorry about that.

**Comment by dgoeries** [comment]
Hey John. Still the binding code uses Range. Yes, by looking into the traits source code, we could create our own `Range` implementation.
It is not a badly required upgrade, but we still sit on 4.6.0 and would like to move with time.
We completely rely on the numpy types because of the serialization of our `Hash`, if you remember. We need to distinguish between `int8`, `int16`, etc. and if we simply have a python `int`, we cannot do that.

Of course we would prefer having such code maintained upstream, that is why I am asking here :-). However, if enthought developers believe the current `Range` implementation is correct (and numpy type not a bug) it is okay as well. We just need to know.

All the best!

**Comment by jwiggins** [comment]
> We completely rely on the numpy types because of the serialization of our `Hash`, if you remember. We need to distinguish between `int8`, `int16`, etc. and if we simply have a python `int`, we cannot do that.

Right. `Hash` and its expectation of typed integer values... _sigh_

Looking at a copy of the code with HEAD@b6ea0c0590e45e891d0c662451fcd78e166a6df0:
`karabogui.binding.config:extract_configuration` should be the only, or one of the few places where you need to worry about transmitting the correct type information to a `Hash` instance. In that function, there's a local function named `_get_binding_value` which could theoretically use the type of the binding to cast the values before assignment to the `Hash`. Other than that, maybe just some unruly (😬) editor controller code would need to be dealt with? Three years is a long time for code under active development.

If the above is still possible, that would almost certainly be a better route that creating a custom trait type. Hopefully test coverage is still good.

**Comment by dgoeries** [comment]
Sorry for late reply, we are in the stress of a release now. Yes the `extract_configuration` could be a possibility to cast it again. Have to check carefully, thanks!

**Comment by mdickinson** [comment]
Indeed this was a deliberate change. As @kitchoi mentions, consistency is relevant here. The scalar types like `Int`, `Float` and `Bool` all normalize their values to be of exact type `int`, `float` or `bool` respectively. The idea is that readers of traited attributes don't get surprises - someone reading a `Float` trait should be reasonably confident that they're going to get a `float` back. (In the past, before this normalization, we've had UI bugs resulting from `np.bool_` instances being passed to UI components where a regular Python `bool` was expected - it turned out that Qt/PyQt didn't like that very much.)

Similarly, as much as possible, an integer-valued `Range` should behave just like `Int`, except with the additional boundedness validation. I'd be quite reluctant to re-introduce the old behaviour and break compatibility between `Range` and `Int`.

**Comment by mdickinson** [comment]
Closing here; thanks for the report and the discussion.
