### ISSUE TITLE
Resolve how NoDefaultSpecified singleton or class should be exposed and documented

### ISSUE THREAD

**Issue by kitchoi** [enthought/traits#1379]
In order to fix documentation build, the `NoDefaultSpecified` singleton instance in `traits.trait_type` is renamed to `no_default_specified` because it was name shadowing the `NoDefaultSpecified` _class_` (see https://github.com/enthought/traits/pull/1378).

Currently `NoDefaultSpecified` is not exposed in `traits.api`, but it is nonetheless in a publicly named module, with a public-looking name (i.e. there are no preceding underscores anywhere in its import name).
I found downstream usage (very old and private code) that looks like this:
```
from traits.trait_handlers import NoDefaultSpecified

class CustomTraitType((TraitType):
    def __init__(self, default_value=NoDefaultSpecified, **metadata):
        ...
```

Given `NoDefaultSpecified` is no longer defined in `trait_handlers`, the above example would not work, but the use case is still sound.

If `NoDefaultSpecified` is indeed used downstream for defining a custom trait type, #1378 would have broken those usages and an alternative will need to be put in place.

**Comment by mdickinson** [comment]
I think we have two options:

- Revert the effects of #1378 (the documentation build issue can be fixed simply in the documentation), or
- Take the opportunity to make `NoDefaultSpecified` and its instance private, undocument it, and remove it from the traits stubs.

Out of the two, I prefer the second option - I think we have reasonably good evidence that any existing uses are either (a) in dead code, or (b) broken, or (c) both.

I don't think we should leave the code in its current state, where `NoDefaultSpecified` is still available for import, but its meaning has changed (it's now a class instead of an instance); that could cause subtle breakage, and I'd rather any breakage be immediate and obvious (e.g., a failed import).
