### ISSUE TITLE
Wildcard searches in traits mini-language

### ISSUE THREAD

**Issue by corranwebster** [enthought/traits#1435]
It is a fairly common requirement to detect any trait change on an object, so there should be a straightforward way to express that in the mini-language.  Currently the only way is by using something like `match(lambda n, t: True)` which while documented is not nice, and is not part of the mini-language.  Improving this is high priority, as it is impacting people working with the `observe` system

In the `on_trait_change` mini-language a bare `+` could be used in this manner, so that would be the simplest to support when migrating.  However an alternative notation would be acceptable (eg. `*` would be well-understood).

It may also make sense to have a short hand in the expression world as well (eg. `any_trait()`) as a synonym for `match(lambda n, t: True)`), which should be straightforward to implement.

**Comment by mdickinson** [comment]
I'm removing the "high priority" label for now; we likely need to have a further discussion on the prioritization of this with respect to things like fixing existing bugs.

**Comment by mdickinson** [comment]
Agreed that `*` seems like the obvious thing to use, even given the mismatch with the existing on_trait_change mini-language.

+1 on an `anytrait` method, too (but let's spell it `anytrait` rather than `any_trait` for consistency, and to avoid confusion).

**Comment by kitchoi** [comment]
> Agreed that * seems like the obvious thing to use, even given the mismatch with the existing on_trait_change mini-language.

Not only mismatch, on_trait_change uses * for recursion.

**Comment by aaronayres35** [comment]
Another related point that came up recently is that using `match(lambda n, t: True)` will cause problems when trying to unobserve (i.e. using `observe(____, match(lambda n, t: True), remove=True`) since in the unobserve statement a new lambda function will be defined that won't compare equal to the original.  In other words you would need to store the original lambda function and reuse it when unhooking the observer but that can be clunky.
See comment: https://github.com/enthought/traitsui/pull/1623#discussion_r622360826

**Comment by beftekhari** [comment]
We recently switched from `on_trait_change` to `observe` and found multiple instances of `.+`, to detect any trait change on objects in a list. I think we will have more usecases for it in the future, too. A short hand expression for `observe` does seem nice.
