### ISSUE TITLE
`=traits-6.1.1` fails tests with `Documenter.add_content() got an unexpected keyword argument 'no_docstring'`

### ISSUE THREAD

**Issue by TheChymera** [enthought/traits#1731]
This is the build log, I know it's an older version, but it would be cool if we could keep supporting it: https://ppb.chymera.eu/efe6c9.log

**Comment by mdickinson** [comment]
Traits 6.1 is beyond end-of-life, I'm afraid, so we won't be issuing any more bugfix releases for the 6.1 series.

Does the issue persist with the most recent Traits release?
What version of Sphinx are you using?

**Comment by mdickinson** [comment]
It looks as though this was fixed in mid-2021 in https://github.com/enthought/traits/pull/1475, so upgrading to Traits version 6.3 or later should fix this for you.

I'll close here, since it looks as though this is fixed in `main`, but please do comment here or open a new issue if you find that the issue persists with the newest Traits.
