### ISSUE TITLE
Cython port: distribute ctraits.c as part of source distribution

### ISSUE THREAD

**Issue by jvkersch** [enthought/traits#314]
See https://github.com/enthought/traits/pull/313#discussion_r66934201

**Comment by mdickinson** [comment]
I agree with the removal of the question mark. :-)

That is, by default, someone doing `pip install traits` to do an install from source should end up compiling the existing `ctraits.c` rather than running cython on the `.pyx` file and using that. Otherwise we'll end up with problems when a user happens to have updated their Cython to a new version that isn't compatible with the Traits source.

**Comment by corranwebster** [comment]
We ship .c files generated by Cython in other projects (Enable and Chaco at least, I think).  So +1 on this.

**Comment by jvkersch** [comment]
@corranwebster Do you commit the Cython generated file to the git repo, or do you generate it on the fly when building the source distribution?

**Comment by itziakos** [comment]
>We ship .c files generated by Cython in other projects (Enable and Chaco at least, I think).

For enable we do not `ship` the *.c files  (actually we do not even have the pyx files either). We only provide cython *.c files for Chaco.
