### ISSUE TITLE
allow_none given to Date and Time are not respected

### ISSUE THREAD

**Issue by kitchoi** [enthought/traits#495]
`allow_none` value given to `Date` and `Time` are not respected.

To reproduce:
```
# tmp.py
import datetime
from traits.api import HasTraits, Date, Time, Instance


class Foo(HasTraits):
    date = Date(allow_none=False)
    time = Time(allow_none=False)
    instance_date = Instance(datetime.date, allow_none=False)
    instance_time = Instance(datetime.time, allow_none=False)


foo = Foo()
```

Expected these two lines to raise TraitError, but they pass:
```
In [1]: %run tmp.py

In [2]: foo.date = None

In [3]: foo.time = None

```

One can workaround using `Instance`:
```
In [4]: foo.instance_date = None
---------------------------------------------------------------------------
TraitError                                Traceback (most recent call last)
<ipython-input-4-fa663306bb41> in <module>()
----> 1 foo.instance_date = None

/Users/kchoi/.edm/envs/resist-py36/lib/python3.6/site-packages/traits/trait_handlers.py in error(self, object, name, value)
    234         """
    235         raise TraitError(
--> 236             object, name, self.full_info(object, name, value), value
    237         )
    238 

TraitError: The 'instance_date' trait of a Foo instance must be a date, but a value of None <class 'NoneType'> was specified.

In [5]: foo.instance_time = None
---------------------------------------------------------------------------
TraitError                                Traceback (most recent call last)
<ipython-input-5-adf6a97a17be> in <module>()
----> 1 foo.instance_time = None

/Users/kchoi/.edm/envs/resist-py36/lib/python3.6/site-packages/traits/trait_handlers.py in error(self, object, name, value)
    234         """
    235         raise TraitError(
--> 236             object, name, self.full_info(object, name, value), value
    237         )
    238 

TraitError: The 'instance_time' trait of a Foo instance must be a time, but a value of None <class 'NoneType'> was specified.


```

**Comment by mdickinson** [comment]
Part of the problem is that `Date` is a bit of a cheat: unlike things like `Int` and `Float`, `Date` isn't a *subclass* of `TraitType`; it's an [*instance* of `TraitType`](https://github.com/enthought/traits/blob/5b14c92c5b01cd54e7dbb56ce67ae2a65b7e25bb/traits/trait_types.py#L3813).

As a result of this, `Date(allow_none=False)` goes through the evil magic of [`TraitType.__call__`](https://github.com/enthought/traits/blob/5b14c92c5b01cd54e7dbb56ce67ae2a65b7e25bb/traits/trait_handlers.py#L613-L616), which attempts to produce a new `TraitType` instance by cloning. That bypasses `BaseInstance.__init__`, which is a Bad Thing.

**Comment by mdickinson** [comment]
So the easy fix would be to make `Date` an actual `TraitType` factory, like `Int` and `Float`. But we should also understand why the current code fails.

(All this applies equally to `Time`, of course.)

**Comment by mdickinson** [comment]
Yep, the bypassing of the `__init__` method by `clone` is exactly the issue here.

`BaseInstance(datetime.date)` has an attribute `_allow_none=True`. Cloning with `allow_none=False` copies the existing `_allow_none=True`, and adds a new `allow_none=False`, which has no effect (because it's the `BaseInstance.__init__` that processes that `allow_none`.)

```
>>> foo = BaseInstance(datetime.date, allow_none=False)
>>> bar = BaseInstance(datetime.date).clone(allow_none=False)
>>> foo.__dict__
{'_allow_none': False, 'adapt': 0, 'module': '__main__', 'klass': <class 'datetime.date'>, 'default_value': None, '_metadata': {'copy': 'deep', 'instance_handler': '_instance_changed_handler'}}
>>> bar.__dict__
{'_allow_none': True, 'adapt': 0, 'module': '__main__', 'klass': <class 'datetime.date'>, 'default_value': None, '_metadata': {'copy': 'deep', 'instance_handler': '_instance_changed_handler', 'allow_none': False, 'parent': <traits.trait_types.BaseInstance object at 0x1205a62e8>}}
```

**Comment by mdickinson** [comment]
Long term, I'd really like to get away from the auto-instantiation of `TraitType`s in `HasTraits` classes: i.e., the ability to use `foo = Int` instead of the more correct `foo = Int()`. That would allow us to fix this issue by replacing the current `Date` with a simple `TraitType` factory function. That fix won't work right now, because if `Date` were just a `TraitType` factory function then a trait declaration `foo = Date` won't get autoinstantiated to `foo = Date()`, so we'll potentially break existing code. The autoinstantiation looks for a subclass of `TraitType`.

**Comment by mdickinson** [comment]
The *other* possible fix here is to override or extend `TraitType.clone` in `BaseInstance`, so that it does the right thing with an `allow_none` argument.

**Comment by mdickinson** [comment]
> The _other_ possible fix here is to override or extend `TraitType.clone` in `BaseInstance`

On reflection, this is the right fix (at least for now).

**Comment by mdickinson** [comment]
Note: this issue will also likely apply to the `Datetime` class (introduced since this issue was opened).

**Comment by mdickinson** [comment]
#1432 fixes this for `Date`, but not for `Time` or `Datetime`.
