### ISSUE TITLE
Long type deleted?

### ISSUE THREAD

**Issue by fred4ets** [enthought/traits#643]
Hi,

It seems that Long type has disappeared in las t version from git source.

So, for instance, Mayavi fails to start:

File "/usr/local/lib/python3.7/dist-packages/mayavi-4.7.2.dev0-py3.7-linux-x86_64.egg/tvtk/pyface/picker.py", line 24, in <module>
    from traits.api import HasTraits, Trait, Long, Array, Any, Bool, Float, \
ImportError: cannot import name 'Long' from 'traits.api' (/usr/local/lib/python3.7/dist-packages/traits-6.0.0.dev1284-py3.7-linux-x86_64.egg/traits/api.py)

Am I doing something wrong?

Thanks in advance.

PS : Python 3.7.3, Traits 6.0.0 dev 1284

**Comment by mdickinson** [comment]
Yes, the `Long` type was deleted: Traits master is now aimed at the 6.0.0 release, which drops support for Python 2.

See also enthought/mayavi#868.

**Comment by mdickinson** [comment]
I could be persuaded that we should keep a backwards compatibility alias `Long` in Traits 6.0.0 (defined simply as `Long = Int`), and then remove that in Traits 6.1.0, or at a point where all affected projects (which seems to be just Mayavi at this point) have had the chance to both fix their uses of `Long` and to make a release containing those fixes.

We'll need to be proactive about identifying and fixing existing uses of `Long`, though; there's no easy way to deprecate so that users get noisy warnings about the pending removal.

(And if we're adding `Long` back, we should probably also add `CLong` for completeness, though as far as I can tell `CLong` really is unused anywhere else.)

**Comment by corranwebster** [comment]
Given that `Long` has been superfluous for many years, and that replacing is straightforward, I think that a better approach is to coordinate releases amongst the ETS libraries around the release of Traits 6.0.  Either release updated versions of packages like Mayavi immediately before or concurrently with Traits 6.0

**Comment by mdickinson** [comment]
@corranwebster That was my first thought too, but given that it's cheap and easy to add `Long` back as an alias for `Int`, and that that then frees us from having to align release schedules, it seems like a win overall. We can open an issue to remind us to remove in 6.1.0.

**Comment by mdickinson** [comment]
To crystallize things: my main problem with *not* re-instating `Long` is that it puts a Mayavi release on the critical path for making the Traits 6.0.0 release. (I don't think breaking Mayavi is an option we should consider, given the number of projects that rely on it.)

**Comment by corranwebster** [comment]
Actually, I'm having something of a re-think based on #648 - if we are keeping `Str`/`Unicode` as aliases, then it is fine to keep `Int`/`Long`.  It would make sense to deprecate and remove these legacy trait types at the same time.

So maybe deprecate `Long` and `Unicode` in 6.0 and remove at some future point (`Unicode` will be a bit more work than `Long` to remove).
