### ISSUE TITLE
Some list events from slice actions have index 0

### ISSUE THREAD

**Issue by k2bd** [enthought/traits#772]
`TraitListObject`'s `__setitem__` and `__delitem__` create list events whose `index` is 0 in some cases where the expectation would probably be a slice:
https://github.com/enthought/traits/blob/d8d851e72ae9d32920eb9216a583484dda0dc4e1/traits/tests/test_traits.py#L1100-L1105

This happens if the start of the slice is 0 or `None`. Originates from this line and the analogous line in `__delitem__`:
https://github.com/enthought/traits/blob/d8d851e72ae9d32920eb9216a583484dda0dc4e1/traits/trait_list_object.py#L131-L135

The comment suggests this is intentional for bug-for-bug compatibility with a previous version, with a patch for Python 3 due to #334.

**Comment by mdickinson** [comment]
Unlike the extra brackets change (#771), I don't think this is something we can easily change without causing breakage. I'm fairly sure there's code out there that expects the index to be a plain integer in at least some circumstances, so making it always a slice isn't an option.

What I *hope* is currently the case is that the index is a slice whenever the step is something other than `1`, and a plain integer otherwise.

If that's true, we should document it clearly. If it's not true, we may consider smoothing the edge cases that make it not true.

**Comment by mdickinson** [comment]
Adding this to the 6.0 milestone. The action to be taken right now is to check *when* we get an index and when we get a slice, and document the answer (possibly tweaking corner-case behaviour if that makes sense).

**Comment by corranwebster** [comment]
I've looked through the code, and I can confirm the following:

- `__setitem__` returns a slice as the index when the step is not 1 (or None, which is equivalent)
- when the step is 1, it returns the start of the slice as the index (or 0 if the start is None)
- `__delitem__` has the same behaviour

I don't think any other methods use or return slices.

I think this may have been due to initially the `TraitsListObject` not handling slices with steps at all; and then having a fix applied.

Required action is to document this.
