### ISSUE TITLE
TraitListObject does not notify if an operation keeps the list unchanged.

### ISSUE THREAD

**Issue by midhun-pm** [enthought/traits#972]
The `TraitListObject` does not notify if an operation such as `__setitem__` does not change the underlying list. i.e. For example, if you have a list `lst=[1,2,3]`, then setting `lst[0] = 1` does not fire an event. 

Is this desirable ?
Does it make more sense to not have this smartness builtin ?

The comparison of added and removed values is done with `__eq__` and may sometimes fail.

**Comment by mdickinson** [comment]
Here's an example of the behaviour: https://github.com/enthought/traits/blob/d7b6d64f07e20ed2ac73db70700dbea374638397/traits/trait_list_object.py#L206

**Comment by kitchoi** [comment]
This discussion came up a few times and I think the consensus has been to remove this equality check.
Please correct me if I got this wrong though.

**Comment by mdickinson** [comment]
> I think the consensus has been to remove this equality check.

Yes, please! It _is_ a behaviour change, so we'll want to make sure that we remember to include notification of that change in the release notes, but I do think it's a change we want to make.

**Comment by kitchoi** [comment]
This has been mentioned offline, just noting here for future reference:
One of the new features to be supported by `observe` (see #977 and [EEP3](https://github.com/enthought/ets/blob/master/docs/source/eeps/eep-3.rst)) is to be able to observe and notify for trait changes inside nested containers.  In the event of having containers inside a `TraitList`, e.g. a nested list of list, it is important that `TraitList` does not silence notifications even when the new values compare equally to the old values, otherwise `observe` cannot maintain the downstream observers/notifiers for the nested containers.
